version: "3"
services:
  caddy:
    image: tylersmith/caddy
    ports:
      - 80:80
      - 443:443
    environment:
      ACME_AGREE: "true"
      CADDYPATH: "/etc/caddycerts"
    volumes:
      - ./.caddy:/etc/caddycerts
      - ./Caddyfile:/etc/Caddyfile
      - /var/log/caddy:/var/log/caddy
    restart: always
    networks:
      - frontend
      - backend
    depends_on:
      - snowglobe1
  snowglobe1: &snowglobe
    image: sherpacash/snowglobed:snowglobe
    ports:
      - 8333:8333
      - 8334:8334
      - 8335:8335
    environment:
      SNOWGLOBE_ENABLE_DURABLE_AUDIT: "false"
      GRPC_GO_LOG_VERBOSITY_LEVEL: 99
      GRPC_GO_LOG_SEVERITY_LEVEL: "info"
    entrypoint:
      [
        "/opt/bchd",
        "--configfile=/bchd.conf",
        "-d=info",
        "--fastsync",
      ]
    volumes:
      - /opt/snowglobe/rpc.key:/rpc.key
      - /opt/snowglobe/rpc.cert:/rpc.cert
      - /opt/snowglobe/bchd.conf:/bchd.conf
      - /var/lib/snowglobe1:/var/lib/snowglobe
    restart: on-failure
    logging:
      options:
        max-file: "1"
        max-size: "100M"
    networks:
      - backend
  snowglobe2:
    <<: *snowglobe
    ports:
      - 8433:8333
      - 8434:8334
      - 8435:8335
    entrypoint:
      [
        "/opt/bchd",
        "--configfile=/bchd.conf",
        "-d=debug",
        "--fastsync",
      ]
    volumes:
      - /opt/snowglobe/rpc.key:/rpc.key
      - /opt/snowglobe/rpc.cert:/rpc.cert
      - /opt/snowglobe/bchd.conf:/bchd.conf
      - /var/lib/snowglobe2:/var/lib/snowglobe
  snowglobe3:
    <<: *snowglobe
    ports:
      - 8533:8333
      - 8534:8334
      - 8535:8335
    entrypoint:
      [
        "/opt/bchd",
        "--configfile=/bchd.conf",
        "-d=info",
        "--fastsync",
      ]
    volumes:
      - /opt/snowglobe/bchd.conf:/bchd.conf
      - /var/lib/snowglobe3:/var/lib/snowglobe
networks:
  frontend:
  backend:
